Feature/add gitplatform support
haevg-rz/git-file-downloader pull request #21
Opened 2024-11-07 10:08 UTC by Driema

2024-11-14 12:42 UTC, RobinHAEVG commented on README.md
> +With this (windows and linux) tool you can now download these config files from an on-promise instance of your choice (GitHub, AzureGit, GitLab) and save them to your disk.
*on-premise

2024-11-14 13:09 UTC, Driema commented on README.md
> +With this (windows and linux) tool you can now download these config files from an on-promise instance of your choice (GitHub, AzureGit, GitLab) and save them to your disk.
Will be handled in seperate PR #22

2025-01-06 07:27 UTC, RobinHAEVG requested changes
Gibt einige Sachen, die Verbesserungen vertragen können

2025-01-06 07:27 UTC, RobinHAEVG commented on README.md
> +With this (windows and linux) tool you can now download these config files from an on-promise instance of your choice (GitHub, AzureGit, GitLab) and save them to your disk.
*on-premise
*save them to disk (reicht aus, ist ja nicht die Festplatte von jemand Fremden)

2025-01-06 07:27 UTC, RobinHAEVG commented on cmd/gdown/main.go
> +	"syscall"
Imports sortieren

2025-01-06 07:27 UTC, RobinHAEVG commented on cmd/gdown/main.go
> +	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
Fasse die Erstellung d. Channels und und das Notify zusammen mit NotifyContext und nutze den Context, um festzustellen, ob die Anwendung beendet werden soll.

2025-01-06 07:27 UTC, RobinHAEVG commented on cmd/gdown/main.go
> +	log.GracefulShutdown.Wait()
was hat der Logger mit graceful shutdown zu tun?

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/api.go
> +// IGitApi Describes the expected behaviour of the gitLabApi.
gitLabApi?

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/api.go
> +// SharedConfig base struct for all implementations of IGitApi.
Mach einen vollständigen Satz draus

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/api.go
> +type GitRepoFile struct {
hier werden keine Tags für die Feldnamen benötigt?

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/api.go
> +	Path string
hier werden keine Tags für die Feldnamen benötigt?

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/api.go
>  		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
Nicht sinnvoll bzw. sicher

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/api.go
> +		req.Header.Add(key, val)
Existierende Header werden dadurch nicht überschrieben und können mehrfach auftreten

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/azuregit.go
> +	azureFileTemplate = "%s/%s/%s/_apis/git/repositories/%s/items?scopePath=%s&versionDescriptor.version=%s&api-version=7.1"
Macht es wirklich Sinn, die Version zu hard-coden?

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/azuregit.go
> +func NewAzureGitApi(auth, userAgent, url, organization, project, repo string) *AzureGitApi {
Parameter ggfs. semantisch unterteilen und BaseConfig und AzureConfig o.Ä.

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/azuregit.go
> +	err = json.Unmarshal(body, &branches)
die Variable branches ist an der Stelle schon ein Pointer

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/api/github.go
> +				"X-GitHub-Api-Version": "2022-11-28",
Ggfs. auch als Parameter akzeptieren

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/cli/azure/cmd.go
> +	globalOptions "github.com/haevg-rz/git-file-downloader/pkg/cli/options"
Imports sortieren

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/cli/github/cmd.go
> +	globalOptions "github.com/haevg-rz/git-file-downloader/pkg/cli/options"
Imports sortieren

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/cli/options/options.go
> +		UserAgent: "Go-http-client/1.1",
Sinnvoller User-Agent?

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/cli/version/cmd.go
>  func init() {
leer, kann daher weg

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/log/logger.go
> +	"github.com/haevg-rz/git-file-downloader/pkg/exit"
Imports sortieren

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/log/logger.go
> +	GracefulShutdown sync.WaitGroup
Nicht aussagekräftig. Typisch ist eine Variable oder ein Feld mit Namen Wg

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/log/logger.go
> +	logFile, err := os.OpenFile(fmt.Sprintf("%s/%s-log.txt", outputPath, time.Now().Format(FilenameFormat)), os.O_CREATE, 0644)
Es gibt auch die Dateiendung *.log*.

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/log/logger.go
> +func InitFileLog(outputPath string, logLevel int, doneCh chan bool) error {
logLevel basiert eig. auf der jeweiligen Nachricht

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/log/logger.go
> +	return &Logger{level: 0}
Unnütz

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/logic/logic.go
> +	globalOptions "github.com/haevg-rz/git-file-downloader/pkg/cli/options"
Import sortieren

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/logic/logic.go
>  type IGitFileDownloader interface {
Das I-Präfix ist DotNet-typisch, aber nicht für Go

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/logic/logic.go
> +	Handle(string, string, string, string) (bool, error)
Was tun die Methoden? Fehlende Export-Kommentare

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/logic/logic.go
> -	files, err := g.gitLabApi.GetFilesFromFolder(repoFolderPath, branch)
Was ist mit Unterordnern und deren Dateien?

2025-01-06 07:27 UTC, RobinHAEVG commented on pkg/mode/mode.go
> +package mode
Ist dieses package wirklich nützlich?

2025-01-06 10:15 UTC, Driema commented on pkg/api/api.go
> +type GitRepoFile struct {
Nein. Instanzen von dem Struct werden im Code erzeugt. Also nicht per json.Unmarshal(...).

2025-01-06 10:16 UTC, Driema commented on pkg/api/api.go
> +	Path string
Wie oben erwaehnt.

2025-01-08 07:31 UTC, Driema commented on pkg/api/api.go
>  		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
War das nur auf die Header bezogen? Oder gab es noch weitere Gruende?

2025-01-08 07:54 UTC, RobinHAEVG commented on pkg/api/api.go
>  		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
Das war auf die TLS Config InsecureSkipVerify bezogen

2025-02-17 13:33 UTC, RobinHAEVG approved these changes

2025-02-17 13:37 UTC, merged